netty:
  port: 8080
  boss-threads: 1
  worker-threads: 4

storage:
  http:
    max-content-length: 65536
    max-file-size: 10737418240
    max-file-chunk-size: 10485760
    file-download-chunk-size: 65536