netty:
  port: 8081
  boss-threads: 1
  worker-threads: 4
  start-timeout-sec: 5

storage:
  http:
    max-content-length: 5242900 # 5mb + 20b
    max-file-size: 10737418240 # 10 gb
    file-download-chunk-size: 65536 # 64 kb

  repository:
    user-data-bucket:
      name: user-data

  auth:
    jwt-token-expiration-sec: 86400 # 24 hours

  quotas:
    default-storage-limit: 10737418240