netty:
  http-port: 8080
  https-port: 8443
  boss-threads: 1
  worker-threads: 4
  start-timeout-sec: 5
  enable-https: true

storage:
  http:
    max-aggregated-content-length: 5242900 # 5mb + 20b
    max-file-size: 10737418240 # 10 gb
    max-file-chunk-size: 10485760 # 10 mb
    file-download-chunk-size: 65536 # 64 kb
    send-upload-progress-interval: 10 # in chunks

  repository:
    minio:
      min-file-part-size: 5242880 # 5mb
    user-data-bucket:
      name: user-data

  auth:
    access-token-expiration-sec: 900 # 15 min
    refresh-token-expiration-sec: 2592000 # 30 days

  quotas:
    default-storage-limit: 10737418240