netty:
  port: 8080
  boss-threads: 1
  worker-threads: 4

storage:
  http:
    max-content-length: 65536 # 64 kb
    max-file-size: 10737418240 # 10 gb
    max-file-chunk-size: 10485760 # 10 mb
    file-download-chunk-size: 65536 # 64 kb
    send-upload-progress-interval: 10 # in chunks

  repository:
    user-data-bucket:
      name: user-data

  auth:
    jwt-token-expiration-ms: 86400000 # 24 hours